server:
  port: 8090

spring:
  application:
    name: Insolvent
  datasource:
    username: root
    password: ostentatious
    url: jdbc:postgresql://localhost:5432/insolvent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true